### ISSUE TITLE
Who do you *compare* yourself to or *aspire* to be like?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/apprenticeship#11]
`unless` you're a Buddhist Monk (_who's only objective in life is to relinquish all worldly possessions and empty their mind to achieve a higher state of consciousness ..._) it's _human nature_ to compare ourselves to _someone_ `else`.  

> For example I compare myself to Paul Graham https://twitter.com/paulg and _aspire_ to his level of both personal and professional success (_however "improbable" that may seem_). 
I've read all his essays http://paulgraham.com/articles.html e.g: http://paulgraham.com/wealth.html and watched _every_ Video I can find on YouTube https://www.youtube.com/results?search_query=Paul+Graham 
If you're going to compare yourself to anyone, there's _no point_ comparing one's self to people who _less_ focussed, determined or "_successful_". 

@iteles, @edwardcodes, @ZooeyMiller & @finnhodgkin please share (_if you feel comfortable doing so_),
I'd *love* to read your thoughts on this.

If you prefer _not_ to compare yourself to others because you are pursuing some ["Zen"](https://zenhabits.net/lifes-enough-stop-comparing-yourself-to-others/) that's _fine_, just acknowledge with a comment. 😉

**Comment by ZooeyMiller** [comment]
I _try_ to only compare myself to myself. 

> _["Who am I better than? I'm better than I used to be, I'mma keep on getting better so you better just get used to me"](https://www.youtube.com/watch?v=ZikWfrGG9kU)_
>
> Scroobius Pip

Not because of Zen or self-actualisation, I just don't want to compare myself to others.

In actuality I compare myself to everyone for everything and exist in a constant state of self doubt. I don't do this because I see a point in it, but because I can't help myself.

**Comment by finnhodgkin** [comment]
Hmm there are tons of people I admire, less that I also compare myself to. Without meeting people IRL it's hard to know what they're _really_ like (and even then can be difficult). Most of my personality comes from quirks in mood or emotions, not political leanings and technical views. I don't compare myself to people I admire because generally they're just random cool people who say nice things and do cool stuff. I'm only just starting to do cool stuff again (career switch woop) so I don't want to feel disappointed by dream-big comparing. 

A list of people I admire and would like to eventually be like:

+ Cory Doctorow - writes cool books, drinks cold brew coffee, edits an awesome tech blog and is big in the Creative Commons and gift economy scenes.
+ Caroline Lucas - almost never says a bad thing politically (except maybe GMO - genetic modification is future!)
+ My family - children's rights activists and scientists (genetics).

**Comment by ghost** [comment]
In my point of view, it's pointless to compare yourself to someone else because everyone is unique so every time we try to compare ourselves to any one else, that comparison will not be accurate , what's better than being a Buddhist monk? That's the goal! 😋

**Comment by nelsonic** [comment]
Thanks gents. v. insightful. 🤓 
we (I) need a (_much_) better way of asking "existential" questions in the future. 
thanks for reminding me. 👍
