### ISSUE TITLE
Got a Smartphone? Which App(s) do you Open First in the Morning? (& Why?)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/apprenticeship#9]
If you are lucky enough to be one of the 2.32 billion people (i.e. Less than a third of the world) who have a smartphone, which app(s) do you open first each day?

Does the app you open first have notifications? Are the notifications the "prompt" to open the App or is there another reason (please specify).

Also, when you are "bored" what do you do? (Is there an app you open, or do you have another way of "curing" your boredom?)

**Comment by iteles** [comment]
When I'm in the UK I often switch on the live news in the BBC app whilst I'm getting ready, but whilst still in bed, I check two things to get me set up for the day:
+ My [github to do list](https://github.com/orgs/dwyl/projects/4) to prime my mind with the day's tasks
+ Instagram (not every day) as I follow some pretty creative people and use this for a little boost

However, when I'm not on a structured schedule, my usage looks pretty different:
_Last 24 hours:_
![24 hours phone stats](https://user-images.githubusercontent.com/4185328/28716073-10a03606-7393-11e7-9e0d-5ebcc09447c7.jpg)

_Last 7 days:_
![7 days phone stats](https://user-images.githubusercontent.com/4185328/28716074-10a20e54-7393-11e7-8482-86163ae469f9.jpg)


What I really aim to do is open a book first in the morning rather than a phone.

**Comment by nelsonic** [comment]
Still think this is a relevant question, possibly one we can include in our on-boarding questionnaire: https://github.com/dwyl/fields-demo/issues/2
